name: Publish Python Package

on:
  push:
    tags:
      - "v*" # Trigger the action only when a tag matching "v*" is pushed (e.g., "v1.0.0").

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Maturin
        run: pip install maturin

      - name: Publish to PyPI
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} # The PyPI API token stored in GitHub secrets
        run: maturin publish --username __token__ --password $MATURIN_PASSWORD
